services:
  api:
    build: .
    container_name: cotillonsm-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"        # Podés dejarlo para debug, pero ya no será público
    networks:
      - cotillonsm-net

  db:
    image: postgres:16-alpine
    container_name: cotillonsm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cotillonsm
      POSTGRES_USER: cotillonsm
      POSTGRES_PASSWORD: cotillonorbit07
    volumes:
      - cotillonsm_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"        # Opcional que quede abierto, solo si lo necesitás desde tu PC
    networks:
      - cotillonsm-net

  caddy:
    image: caddy:2-alpine
    container_name: cotillonsm-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cotillonsm-net
    depends_on:
      - api

networks:
  cotillonsm-net:

volumes:
  cotillonsm_db_data:
  caddy_data:
  caddy_config:
